In [3]:
import numpy as np
import pandas as pd

In [4]:
import datetime

In [6]:
trans= pd.read_excel("C:/Users/sonalk/Documents/My Received Files/Transaction_DB_jupyter.xlsx")

In [4]:
trans=pd.DataFrame(trans)

In [5]:
trans.shape

(1050, 35)

**Converting Current System Time to a Pandas Timestamp**

In [10]:
current_time=datetime.datetime.now()
current_time
pd.Timestamp(current_time)

Timestamp('2017-07-17 13:59:10.503000')

**Convert all Date and Time attributes**

In [7]:
trans.DOB=pd.to_datetime(trans.DOB)

In [8]:
trans.dtypes


isFraud                                        int64
Customer_Name                                 object
Card_Number                                    int64
Card_Type                                     object
Gender                                        object
DOB                                   datetime64[ns]
Age                                            int64
Base_Location                                 object
Base_Latitude                                float64
Base_Longitude                               float64
Credit_limit                                   int64
Avg_No_of_Transactions                         int64
Currency                                      object
Transaction_Amount                             int64
Current_Balance                                int64
Transaction_Timestamp                 datetime64[ns]
Purchase_Type                                 object
Merchant_Type                                 object
Merchant_Code                                 

**Code for calculating # Transactions in Last 24 hours**

In [11]:
previous_day_timestamp=pd.to_datetime(current_time-datetime.timedelta(1))
previous_day_timestamp

Timestamp('2017-07-16 13:59:10.503000')

In [12]:
trans["Transaction_Timestamp"]=trans["Transaction_Timestamp"].sort_values()

In [13]:
trans["Previous_Day_Transaction_Timestamp"]=pd.to_datetime(trans.Transaction_Timestamp-datetime.timedelta(1))

In [27]:
df=trans.groupby("Card_Number")
df.indices.values()

[array([162, 163, 164, 165, 166, 167, 168, 169, 170, 171], dtype=int64),
 array([622, 623, 624, 625, 626, 627, 628, 629, 630, 631], dtype=int64),
 array([422, 423, 424, 425, 426, 427, 428, 429, 430, 431], dtype=int64),
 array([112, 113, 114, 115, 116, 117, 118, 119, 120, 121], dtype=int64),
 array([412, 413, 414, 415, 416, 417, 418, 419, 420, 421], dtype=int64),
 array([822, 823, 824, 825, 826, 827, 828, 829, 830, 831], dtype=int64),
 array([402, 403, 404, 405, 406, 407, 408, 409, 410, 411], dtype=int64),
 array([482, 483, 484, 485, 486, 487, 488, 489, 490, 491], dtype=int64),
 array([100, 101], dtype=int64),
 array([122, 123, 124, 125, 126, 127, 128, 129, 130, 131], dtype=int64),
 array([772, 773, 774, 775, 776, 777, 778, 779, 780, 781], dtype=int64),
 array([602, 603, 604, 605, 606, 607, 608, 609, 610, 611], dtype=int64),
 array([492, 493, 494, 495, 496, 497, 498, 499, 500, 501], dtype=int64),
 array([352, 353, 354, 355, 356, 357, 358, 359, 360, 361], dtype=int64),
 array([672, 673, 

In [16]:
for i in df.indices.values():
    list=i
    for j in list:
        count=0
        if j==0:
            count=0
            trans.No_of_Transactions_Last_24_hrs[j]=count
        else:
            x=j
            count=0
            while (trans.Transaction_Timestamp[x]>trans.Transaction_Timestamp[j-1]>trans.Previous_Day_Transaction_Timestamp[x]):
                    count=count+1
                    if j>1:
                        j=j-1
                    else:
                        j=2
            else:
                trans.No_of_Transactions_Last_24_hrs[x]=count

C:\Anaconda2\lib\site-packages\ipykernel\__main__.py:18: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
C:\Anaconda2\lib\site-packages\ipykernel\__main__.py:7: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy


**Code to Calculate Amount Transacted in Last 24 Hours**

In [14]:
df=trans.groupby("Card_Number")

In [15]:
for i in df.indices.values():
    list=i
    for j in list:
        amount=0
        if j==0:
            amount=0
            trans.Amount_Transacted_Last_24hrs[j]=amount
        else:
            x=j
            amount=0
            while (trans.Transaction_Timestamp[x]>trans.Transaction_Timestamp[j-1]>trans.Previous_Day_Transaction_Timestamp[x]):
                    amount=amount+trans.Transaction_Amount[j-1]
                    if j>1:
                        j=j-1
                    else:
                        j=2
            else:
              trans.Amount_Transacted_Last_24hrs[x]=amount

C:\ProgramData\Anaconda3\lib\site-packages\ipykernel\__main__.py:18: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
C:\ProgramData\Anaconda3\lib\site-packages\ipykernel\__main__.py:7: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy


In [16]:
list_d=["Transaction_Timestamp","Previous_Day_Transaction_Timestamp","No_of_Transactions_Last_24_hrs","Transaction_Amount","Amount_Transacted_Last_24hrs"]
trans[list_d][:10]

Transaction_Timestamp Previous_Day_Transaction_Timestamp  \
0   2017-03-06 12:42:00                2017-03-05 12:42:00   
1   2017-03-07 06:25:00                2017-03-06 06:25:00   
2   2017-03-08 04:08:00                2017-03-07 04:08:00   
3   2017-03-08 09:06:00                2017-03-07 09:06:00   
4   2017-03-09 00:10:00                2017-03-08 00:10:00   
5   2017-03-11 00:41:00                2017-03-10 00:41:00   
6   2017-03-11 05:04:00                2017-03-10 05:04:00   
7   2017-03-12 04:14:00                2017-03-11 04:14:00   
8   2017-03-13 01:46:00                2017-03-12 01:46:00   
9   2017-03-15 02:40:00                2017-03-14 02:40:00   

   No_of_Transactions_Last_24_hrs  Transaction_Amount  \
0                               0                7705   
1                               1                6177   
2                               1                8386   
3                               1                6773   
4                               2               13394   
5                               0                5105   
6                               1                7972   
7                               1                8561   
8                               1                8992   
9                               0               10408   

   Amount_Transacted_Last_24hrs  
0                             0  
1                          7705  
2                          6177  
3                          8386  
4                         15159  
5                             0  
6                          5105  
7                          7972  
8                          8561  
9                             0

**Code to Calculate Current_Balance**

In [17]:
trans["Transaction_Year"]=pd.DatetimeIndex(trans["Transaction_Timestamp"]).year.tolist()
trans["Transaction_Month"]=pd.DatetimeIndex(trans["Transaction_Timestamp"]).month.tolist()

In [18]:
dr=trans.groupby(["Card_Number","Transaction_Month","Transaction_Year"])

In [19]:
for i in dr.indices.values():
    list=i
    count=0
    for j in list:
        if count==0:
            Current_Balance=trans.Credit_limit[j]-trans.Transaction_Amount[j]
            count=count+1
            trans.Current_Balance[j]=Current_Balance
        else:
            Current_Balance=Current_Balance-trans.Transaction_Amount[j]
            trans.Current_Balance[j]=Current_Balance
    
            

C:\ProgramData\Anaconda3\lib\site-packages\ipykernel\__main__.py:8: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
C:\ProgramData\Anaconda3\lib\site-packages\ipykernel\__main__.py:11: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy


In [20]:
list_e=["Transaction_Timestamp","Transaction_Amount","Credit_limit","Current_Balance"]
trans[list_e][0:10]

Transaction_Timestamp  Transaction_Amount  Credit_limit  Current_Balance
0   2017-03-06 12:42:00                7705        350000           342295
1   2017-03-07 06:25:00                6177        350000           336118
2   2017-03-08 04:08:00                8386        350000           327732
3   2017-03-08 09:06:00                6773        350000           320959
4   2017-03-09 00:10:00               13394        350000           307565
5   2017-03-11 00:41:00                5105        350000           302460
6   2017-03-11 05:04:00                7972        350000           294488
7   2017-03-12 04:14:00                8561        350000           285927
8   2017-03-13 01:46:00                8992        350000           276935
9   2017-03-15 02:40:00               10408        350000           266527

**Code to Calculate Time Difference Since Last Transaction**

In [21]:
df=trans.groupby("Card_Number")
trans["Time_Diff_in_hours"]=0

In [22]:
from math import ceil

In [23]:
for i in df.indices.values():
    list=i
    count=0
    for j in list:
        if count==0:
            time_diff=0
            count=count+1
            trans.Time_Since_Last_Transaction[j]=time_diff
            trans["Time_Diff_in_hours"][j]=count
        else:
            time_diff=trans.Transaction_Timestamp[j]-trans.Transaction_Timestamp[j-1]
            time_diff_days_to_sec=time_diff.days*86400
            tot_sec=time_diff_days_to_sec+time_diff.seconds
            trans.Time_Since_Last_Transaction[j]=time_diff
            trans["Time_Diff_in_hours"][j]=ceil(tot_sec/3600)

C:\ProgramData\Anaconda3\lib\site-packages\ipykernel\__main__.py:8: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
C:\ProgramData\Anaconda3\lib\site-packages\ipykernel\__main__.py:9: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
C:\ProgramData\Anaconda3\lib\site-packages\ipykernel\__main__.py:14: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
C:\ProgramData\Anaconda3\lib\site-packages\ipykernel\__main__.py:15: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a Dat

In [24]:
list_f=["Card_Number","Transaction_Timestamp","Time_Since_Last_Transaction","Time_Diff_in_hours"]
trans[list_f][10:20]

Card_Number Transaction_Timestamp Time_Since_Last_Transaction  \
10  6562037694752940   2017-03-06 02:17:00                           0   
11  6562037694752940   2017-03-07 05:17:00             1 days 03:00:00   
12  6562037694752940   2017-03-07 21:01:00             0 days 15:44:00   
13  6562037694752940   2017-03-10 05:46:00             2 days 08:45:00   
14  6562037694752940   2017-03-10 17:26:00             0 days 11:40:00   
15  6562037694752940   2017-03-11 04:21:00             0 days 10:55:00   
16  6562037694752940   2017-03-12 00:30:00             0 days 20:09:00   
17  6562037694752940   2017-03-12 18:54:00             0 days 18:24:00   
18  6562037694752940   2017-03-12 19:17:00             0 days 00:23:00   
19  6562037694752940   2017-03-14 08:23:00             1 days 13:06:00   

    Time_Diff_in_hours  
10                   1  
11                  27  
12                  16  
13                  57  
14                  12  
15                  11  
16                  21  
17                  19  
18                   1  
19                  38

**Code to Calculate Distance from Last Transaction** 

In [24]:
df=trans.groupby("Card_Number")
df.show()

AttributeError: 'DataFrameGroupBy' object has no attribute 'show'

In [26]:
from math import sin, cos, sqrt, atan2, radians, ceil

In [27]:
for i in df.indices.values():
    list=i
    count=0
    for j in list:
        if count==0:
            distance=0
            count=count+1
            trans.Distance[j]=distance
        else:
            Radius=6373.0
            plat=radians(trans.Transaction_Latitude[j-1])
            plong=radians(trans.Transaction_Longitude[j-1])
            tlat=radians(trans.Transaction_Latitude[j])
            tlong=radians(trans.Transaction_Longitude[j])
            dlong=tlong-plong
            dlat=tlat-plat
            a = sin(dlat / 2)**2 + cos(plat) * cos(tlat) * sin(dlong / 2)**2
            c = 2 * atan2(sqrt(a), sqrt(1 - a))
            distance = Radius * c
            trans.Distance[j]=distance


C:\ProgramData\Anaconda3\lib\site-packages\ipykernel\__main__.py:8: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
C:\ProgramData\Anaconda3\lib\site-packages\ipykernel\__main__.py:20: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy


In [28]:
list_f=["Base_Location","Transaction_Location","Transaction_Latitude","Transaction_Longitude","Distance"]
trans[list_f][:20]

Base_Location Transaction_Location  Transaction_Latitude  \
0        Chennai              Chennai              13.08268   
1        Chennai               Mumbai              19.07598   
2        Chennai                Delhi              28.70406   
3        Chennai              Kolkata              22.57265   
4        Chennai            Bangalore              12.97160   
5        Chennai            Hyderabad              17.38504   
6        Chennai            Ahmedabad              23.02251   
7        Chennai                 Pune              18.52043   
8        Chennai               Mysore              12.29581   
9        Chennai                Surat              21.17024   
10     Bangalore              Chennai              13.08268   
11     Bangalore               Mumbai              19.07598   
12     Bangalore                Delhi              28.70406   
13     Bangalore              Kolkata              22.57265   
14     Bangalore            Bangalore              12.97160   
15     Bangalore            Hyderabad              17.38504   
16     Bangalore            Ahmedabad              23.02251   
17     Bangalore                 Pune              18.52043   
18     Bangalore               Mysore              12.29581   
19     Bangalore                Surat              21.17024   

    Transaction_Longitude     Distance  
0                80.27072     0.000000  
1                72.87766  1033.427783  
2                77.10249  1153.602425  
3                88.36390  1318.162935  
4                77.59456  1561.193319  
5                78.48667   500.154771  
6                72.57136   879.772584  
7                73.85674   518.288725  
8                76.63938   753.852598  
9                72.83106  1067.008614  
10               80.27072     0.000000  
11               72.87766  1033.427783  
12               77.10249  1153.602425  
13               88.36390  1318.162935  
14               77.59456  1561.193319  
15               78.48667   500.154771  
16               72.57136   879.772584  
17               73.85674   518.288725  
18               76.63938   753.852598  
19               72.83106  1067.008614

**Code to Calculate the Avg # of Transactions**

In [29]:
trans["Quarter"]=""
for j in range(0,len(trans)):
    if trans["Transaction_Month"][j] in (4,5,6):
        trans["Quarter"][j]="Q1"
    elif trans["Transaction_Month"][j] in (7,8,9):
        trans["Quarter"][j]="Q2"
    elif trans["Transaction_Month"][j] in (10,11,12):
        trans["Quarter"][j]="Q3"  
    else:
        trans["Quarter"][j]="Q4"
            
    

C:\ProgramData\Anaconda3\lib\site-packages\ipykernel\__main__.py:10: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
C:\ProgramData\Anaconda3\lib\site-packages\ipykernel\__main__.py:4: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
C:\ProgramData\Anaconda3\lib\site-packages\ipykernel\__main__.py:6: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy


In [30]:
list_e=["Quarter","Transaction_Timestamp","Transaction_Month"]
trans[list_e][0:17]

Quarter Transaction_Timestamp  Transaction_Month
0       Q4   2017-03-06 12:42:00                  3
1       Q4   2017-03-07 06:25:00                  3
2       Q4   2017-03-08 04:08:00                  3
3       Q4   2017-03-08 09:06:00                  3
4       Q4   2017-03-09 00:10:00                  3
5       Q4   2017-03-11 00:41:00                  3
6       Q4   2017-03-11 05:04:00                  3
7       Q4   2017-03-12 04:14:00                  3
8       Q4   2017-03-13 01:46:00                  3
9       Q4   2017-03-15 02:40:00                  3
10      Q4   2017-03-06 02:17:00                  3
11      Q4   2017-03-07 05:17:00                  3
12      Q4   2017-03-07 21:01:00                  3
13      Q4   2017-03-10 05:46:00                  3
14      Q4   2017-03-10 17:26:00                  3
15      Q4   2017-03-11 04:21:00                  3
16      Q4   2017-03-12 00:30:00                  3

In [31]:
dr=trans.groupby(["Card_Number","Quarter","Transaction_Year"])

In [32]:
#trans=trans.rename(columns={"Avg_No_of_Transactions(Quarterly)":"Avg_No_of_Transactions"})

In [33]:
for i in dr.indices.values():
    list=i
    for j in list:
        k=len(list)
        trans["Avg_No_of_Transactions"][j]= ceil(k/3)

C:\ProgramData\Anaconda3\lib\site-packages\ipykernel\__main__.py:5: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy


In [34]:
list_f=["Card_Number","Transaction_Timestamp","Avg_No_of_Transactions"]
trans[list_f][:17]

Card_Number Transaction_Timestamp  Avg_No_of_Transactions
0   7470505228653560   2017-03-06 12:42:00                       4
1   7470505228653560   2017-03-07 06:25:00                       4
2   7470505228653560   2017-03-08 04:08:00                       4
3   7470505228653560   2017-03-08 09:06:00                       4
4   7470505228653560   2017-03-09 00:10:00                       4
5   7470505228653560   2017-03-11 00:41:00                       4
6   7470505228653560   2017-03-11 05:04:00                       4
7   7470505228653560   2017-03-12 04:14:00                       4
8   7470505228653560   2017-03-13 01:46:00                       4
9   7470505228653560   2017-03-15 02:40:00                       4
10  6562037694752940   2017-03-06 02:17:00                       4
11  6562037694752940   2017-03-07 05:17:00                       4
12  6562037694752940   2017-03-07 21:01:00                       4
13  6562037694752940   2017-03-10 05:46:00                       4
14  6562037694752940   2017-03-10 17:26:00                       4
15  6562037694752940   2017-03-11 04:21:00                       4
16  6562037694752940   2017-03-12 00:30:00                       4

**Code to Calculate Quarterly Spending**

In [35]:
dr=trans.groupby(["Card_Number","Quarter","Transaction_Year"])
#trans=trans.rename(columns={"Quarterly_Ending_Balance":"Quarterly_Spending"})

In [36]:
trans["Quarterly_Spending"]=0
for i in dr.indices.values():
    list=i
    qtr_transaction_amount=0
    for j in list:
        l=list[-1]
        qtr_transaction_amount=qtr_transaction_amount+trans.Transaction_Amount[j]
        trans["Quarterly_Spending"][l]=qtr_transaction_amount
    for j in list:
        trans["Quarterly_Spending"][j]=qtr_transaction_amount
    

C:\ProgramData\Anaconda3\lib\site-packages\ipykernel\__main__.py:8: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
C:\ProgramData\Anaconda3\lib\site-packages\ipykernel\__main__.py:10: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy


In [37]:
list_f=["Card_Number","Transaction_Timestamp","Quarter","Transaction_Amount","Current_Balance"]
trans[list_f][0:17]

Card_Number Transaction_Timestamp Quarter  Transaction_Amount  \
0   7470505228653560   2017-03-06 12:42:00      Q4                7705   
1   7470505228653560   2017-03-07 06:25:00      Q4                6177   
2   7470505228653560   2017-03-08 04:08:00      Q4                8386   
3   7470505228653560   2017-03-08 09:06:00      Q4                6773   
4   7470505228653560   2017-03-09 00:10:00      Q4               13394   
5   7470505228653560   2017-03-11 00:41:00      Q4                5105   
6   7470505228653560   2017-03-11 05:04:00      Q4                7972   
7   7470505228653560   2017-03-12 04:14:00      Q4                8561   
8   7470505228653560   2017-03-13 01:46:00      Q4                8992   
9   7470505228653560   2017-03-15 02:40:00      Q4               10408   
10  6562037694752940   2017-03-06 02:17:00      Q4                3015   
11  6562037694752940   2017-03-07 05:17:00      Q4                6045   
12  6562037694752940   2017-03-07 21:01:00      Q4                2800   
13  6562037694752940   2017-03-10 05:46:00      Q4                8328   
14  6562037694752940   2017-03-10 17:26:00      Q4                7707   
15  6562037694752940   2017-03-11 04:21:00      Q4                1928   
16  6562037694752940   2017-03-12 00:30:00      Q4                7791   

    Current_Balance  
0            342295  
1            336118  
2            327732  
3            320959  
4            307565  
5            302460  
6            294488  
7            285927  
8            276935  
9            266527  
10           221985  
11           215940  
12           213140  
13           204812  
14           197105  
15           195177  
16           187386

In [38]:
list_f=["Card_Number","Transaction_Timestamp","Quarter","Transaction_Amount","Current_Balance","Quarterly_Spending"]
trans[list_f][0:20]

Card_Number Transaction_Timestamp Quarter  Transaction_Amount  \
0   7470505228653560   2017-03-06 12:42:00      Q4                7705   
1   7470505228653560   2017-03-07 06:25:00      Q4                6177   
2   7470505228653560   2017-03-08 04:08:00      Q4                8386   
3   7470505228653560   2017-03-08 09:06:00      Q4                6773   
4   7470505228653560   2017-03-09 00:10:00      Q4               13394   
5   7470505228653560   2017-03-11 00:41:00      Q4                5105   
6   7470505228653560   2017-03-11 05:04:00      Q4                7972   
7   7470505228653560   2017-03-12 04:14:00      Q4                8561   
8   7470505228653560   2017-03-13 01:46:00      Q4                8992   
9   7470505228653560   2017-03-15 02:40:00      Q4               10408   
10  6562037694752940   2017-03-06 02:17:00      Q4                3015   
11  6562037694752940   2017-03-07 05:17:00      Q4                6045   
12  6562037694752940   2017-03-07 21:01:00      Q4                2800   
13  6562037694752940   2017-03-10 05:46:00      Q4                8328   
14  6562037694752940   2017-03-10 17:26:00      Q4                7707   
15  6562037694752940   2017-03-11 04:21:00      Q4                1928   
16  6562037694752940   2017-03-12 00:30:00      Q4                7791   
17  6562037694752940   2017-03-12 18:54:00      Q4                3443   
18  6562037694752940   2017-03-12 19:17:00      Q4                 255   
19  6562037694752940   2017-03-14 08:23:00      Q4                6960   

    Current_Balance  Quarterly_Spending  
0            342295               83473  
1            336118               83473  
2            327732               83473  
3            320959               83473  
4            307565               83473  
5            302460               83473  
6            294488               83473  
7            285927               83473  
8            276935               83473  
9            266527               83473  
10           221985               48272  
11           215940               48272  
12           213140               48272  
13           204812               48272  
14           197105               48272  
15           195177               48272  
16           187386               48272  
17           183943               48272  
18           183688               48272  
19           176728               48272

**Write Data to Excel**

In [39]:
writer = pd.ExcelWriter('Transaction_DB_jupyter.xlsx')
trans.to_excel(writer,'Sheet1')
writer.save()

**Machine Learning Algos**

# Random Forest

In [40]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split

In [41]:
list_X=['Age',
       'Base_Latitude', 'Base_Longitude', 'Credit_limit',
       'Avg_No_of_Transactions','Transaction_Amount',
       'Current_Balance','Merchant_Code', 'Merchant_Profile_Score',
       'Transaction_Time',
       'Transaction_Latitude', 'Transaction_Longitude', 'Distance',
       'No_of_Transactions_Last_24_hrs', 'Amount_Transacted_Last_24hrs',
       'Transaction_Year',
       'Transaction_Month', 'Time_Diff_in_hours',
       'Quarterly_Spending']

In [42]:
X=trans[list_X][:]
y=trans["isFraud"]

In [43]:
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.3,random_state=0)

In [44]:
clf = RandomForestClassifier().fit(X_train, y_train)
clf.score(X_train,y_train)

0.99727891156462589

In [47]:
from sklearn.metrics import classification_report, confusion_matrix, precision_score
predict_y=clf.predict(X_test)

In [48]:
precision_score(y_test, predict_y)

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\metrics\classification.py:1113: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples.
  'precision', 'predicted', average, warn_for)


0.0

In [49]:
confusion = confusion_matrix(y_test, predict_y)
print(confusion)

[[312   0]
 [  3   0]]


In [50]:
from sklearn.dummy import DummyClassifier

# Negative class (0) is most frequent
dummy_majority = DummyClassifier(strategy = 'most_frequent').fit(X_train, y_train)
y_majority_predicted = dummy_majority.predict(X_test)
confusion_dummy = confusion_matrix(y_test, y_majority_predicted)

print('Most frequent class (dummy classifier)\n', confusion_dummy)

Most frequent class (dummy classifier)
 [[312   0]
 [  3   0]]


**SMOTE**

In [51]:
from imblearn.over_sampling import SMOTE 

In [52]:
sm= SMOTE(random_state=7)

In [53]:
X_sm, y_sm=sm.fit_sample(X,y)

In [54]:
X_sm_train,X_sm_test,y_sm_train,y_sm_test=train_test_split(X_sm,y_sm,test_size=0.3,random_state=7)

In [77]:
clf_sm = RandomForestClassifier(n_estimators=1000, max_depth=4, random_state=7).fit(X_sm_train, y_sm_train)
clf_sm.score(X_sm_train,y_sm_train)

0.99174122505161733

In [79]:
predict_y_sm=clf_sm.predict(X_sm_test)

In [80]:
confusion_sm = confusion_matrix(y_sm_test, predict_y_sm)
print(confusion_sm)

[[308  10]
 [  2 303]]


In [81]:
from sklearn.metrics import *

In [82]:
print(classification_report(y_sm_test, predict_y_sm))

             precision    recall  f1-score   support

          0       0.99      0.97      0.98       318
          1       0.97      0.99      0.98       305

avg / total       0.98      0.98      0.98       623



In [83]:
precision_score(y_sm_test, predict_y_sm)

0.96805111821086265

**Prediction on the Original Dataset**

In [84]:
clf_sm.score(X_train,y_train)

0.98231292517006807

In [85]:
predict_y_exp=clf_sm.predict(X_test)

In [86]:
confusion_matrix(y_test,predict_y_exp)

array([[306,   6],
       [  0,   3]])

In [87]:
precision_score(y_test, predict_y_exp)

0.33333333333333331

In [88]:
print(classification_report(y_test, predict_y_exp))

             precision    recall  f1-score   support

          0       1.00      0.98      0.99       312
          1       0.33      1.00      0.50         3

avg / total       0.99      0.98      0.99       315



In [97]:
new_trans= pd.read_excel("C:/Users/Harshit Rastogi/Documents/VirtusaPolaris/Transaction_DB_jupyter_test.xlsx")

In [98]:
print(clf_sm.predict(new_trans))

[1]


In [102]:
clf_sm.feature_importances_

array([ 0.10992709,  0.03441506,  0.03584814,  0.07361662,  0.01524566,
        0.0295088 ,  0.03449499,  0.01036634,  0.04795117,  0.17219814,
        0.02590298,  0.10813317,  0.07656377,  0.09961481,  0.08376271,
        0.        ,  0.01907698,  0.01391459,  0.00945896])

In [109]:
X_sm=pd.DataFrame(X_sm)
y_sm=pd.DataFrame(y_sm)    
balanced_dataset=pd.concat([y_sm,X_sm], axis=1)

In [105]:
balanced_dataset.to_excel("C:/Users/Harshit Rastogi/Documents/VirtusaPolaris/Balanced_Transactions.xlsx")

In [110]:
balanced_dataset.to_csv("C:/Users/Harshit Rastogi/Documents/VirtusaPolaris/Balanced_Transactions.csv",header=False,index=False)